---
- name: install epel repo
  yum: name=epel-release state=present

- name: install apache
  yum: name=httpd state=present
  
- name: enabled mod_rewrite
  apache2_module: name=rewrite state=present
  notify: restart httpd 
  
- name: Makr Dir for Hello HTML
  file:
    path: /var/www/hello.com/hello_html
    state: directory
    mode: 0755
    owner: apache2
    group: apache2
  
- name: Copy Hello World HTML
  copy:
    file: "index.html"
    dest: "/var/www/hello.com/hello_html/index.html"
  notify: restart httpd
  
