---
- name: install epel repo
  yum: name=epel-release state=present

- name: install apache
  yum: name=httpd state=present
  
- name: enabled mod_rewrite
  apache2_module: name=rewrite state=present
  notify: restart httpd 
  
#- name: Makr Dir for Hello HTML
  file:
    path: /var/www/hello.com/hello_html
    state: directory
    mode: 0755
    owner: root
    group: root
  
- name: Copy Hello World HTML
  copy:
    file: "index.html"
    dest: "/var/www/hello.com/hello_html/index.html"
  notify: restart httpd
  
- name: apache listen on port {{ http_port }}
  lineinfile: 
    dest: /etc/apache/ports.conf
    regexp: "^Listen " 
    line: "Listen {{ http_port }}"
    state: present
    
- name: apache virtualhost on port {{ http_port }}
  lineinfile:
    dest: /etc/apa/sites-available/000-default.conf
    regexp: "^<VirtualHost *:"
    line: "<VirtualHost *:{{ http_port }}>"    
  
- name: create virtual host file
  template: 
    src: virtualhost.conf 
    dest: /etc/apache2/sites-available/{{ domain }}.conf

  
